/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareholdingsRouteImport } from './routes/shareholdings'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeputiesIndexRouteImport } from './routes/deputies/index'
import { Route as DeputiesDeputyIdRouteImport } from './routes/deputies/$deputyId'

const ShareholdingsRoute = ShareholdingsRouteImport.update({
  id: '/shareholdings',
  path: '/shareholdings',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeputiesIndexRoute = DeputiesIndexRouteImport.update({
  id: '/deputies/',
  path: '/deputies/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeputiesDeputyIdRoute = DeputiesDeputyIdRouteImport.update({
  id: '/deputies/$deputyId',
  path: '/deputies/$deputyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/benefits': typeof BenefitsRoute
  '/positions': typeof PositionsRoute
  '/shareholdings': typeof ShareholdingsRoute
  '/deputies/$deputyId': typeof DeputiesDeputyIdRoute
  '/deputies': typeof DeputiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/benefits': typeof BenefitsRoute
  '/positions': typeof PositionsRoute
  '/shareholdings': typeof ShareholdingsRoute
  '/deputies/$deputyId': typeof DeputiesDeputyIdRoute
  '/deputies': typeof DeputiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/benefits': typeof BenefitsRoute
  '/positions': typeof PositionsRoute
  '/shareholdings': typeof ShareholdingsRoute
  '/deputies/$deputyId': typeof DeputiesDeputyIdRoute
  '/deputies/': typeof DeputiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/benefits'
    | '/positions'
    | '/shareholdings'
    | '/deputies/$deputyId'
    | '/deputies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/benefits'
    | '/positions'
    | '/shareholdings'
    | '/deputies/$deputyId'
    | '/deputies'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/benefits'
    | '/positions'
    | '/shareholdings'
    | '/deputies/$deputyId'
    | '/deputies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BenefitsRoute: typeof BenefitsRoute
  PositionsRoute: typeof PositionsRoute
  ShareholdingsRoute: typeof ShareholdingsRoute
  DeputiesDeputyIdRoute: typeof DeputiesDeputyIdRoute
  DeputiesIndexRoute: typeof DeputiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shareholdings': {
      id: '/shareholdings'
      path: '/shareholdings'
      fullPath: '/shareholdings'
      preLoaderRoute: typeof ShareholdingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deputies/': {
      id: '/deputies/'
      path: '/deputies'
      fullPath: '/deputies'
      preLoaderRoute: typeof DeputiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deputies/$deputyId': {
      id: '/deputies/$deputyId'
      path: '/deputies/$deputyId'
      fullPath: '/deputies/$deputyId'
      preLoaderRoute: typeof DeputiesDeputyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BenefitsRoute: BenefitsRoute,
  PositionsRoute: PositionsRoute,
  ShareholdingsRoute: ShareholdingsRoute,
  DeputiesDeputyIdRoute: DeputiesDeputyIdRoute,
  DeputiesIndexRoute: DeputiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
